##uzyj dictionary
question0 = input("Jak masz na imię oraz nazwisko?")
question1 = input("Najczęstszym sposobem spędzania wolnego czasu jest dla Ciebie:")
question2 = input("W jakich okolicznościach czytasz książki najczęściej?")
question3 = input("Jeżeli spędzasz czas wolny czytając książki, jaki jest główny powód takiego wyboru?")
question4 = input("Po książki w jakiej formie sięgasz najczęściej?")
question5 = input("Ile książek czytasz średnio w ciągu roku?")
question6 = input("Jak często średnio czytasz książki?")
question7 = input("Po jakie gatunki książek sięgasz najczęściej?")

print("pytanie: Jak masz na imię oraz nazwisko?")
print("odpowiedz ", question0)
print("pytanie: Najczęstszym sposobem spędzania wolnego czasu jest dla Ciebie:")
print("odpowiedz ", question1)
print("pytanie: W jakich okolicznościach czytasz książki najczęściej?")
print("odpowiedz ", question2)
print("pytanie: Jeżeli spędzasz czas wolny czytając książki, jaki jest główny powód takiego wyboru?")
print("odpowiedz ", question3)
print("pytanie: Po książki w jakiej formie sięgasz najczęściej?")
print("odpowiedz ", question4)
print("pytanie: Ile książek czytasz średnio w ciągu roku?")
print("odpowiedz ", question5)
print("pytanie: Jak często średnio czytasz książki?")
print("odpowiedz ", question6)
print("pytanie: Po jakie gatunki książek sięgasz najczęściej?")
print("odpowiedz ", question7)
